version: "3"

services:
  portainer-ce:
    image: ${REGISTRY_SERVER:-}portainer/portainer-ce
    container_name: portainer-ce
    hostname: portainer-ce
    restart: always
    network_mode: "bridge"
    ports:
      - 9000:9000
    volumes:
      - portainer-data:/data
      - /var/run/docker.sock:/var/run/docker.sock

volumes:
  portainer-data: